ERROR: unable to create snapshot: snapshot with name snap1 already exists
