ERROR: unable to add local repo: local repo with name repo3 already exists
